SET(CMAKE_INSTALL_PREFIX "/home/ysc/jy_cog/slam")

set(CPACK_PACKAGING_INSTALL_PREFIX ${CMAKE_INSTALL_PREFIX})
set(CPACK_PACKAGE_VERSION_MAJOR "2")
set(CPACK_PACKAGE_VERSION_MINOR "1")
set(CPACK_PACKAGE_VERSION_PATCH "0")
set(PRE_RELEASE_VERSION "-alpha")
set(CPACK_GENERATOR "DEB")
set(CPACK_PACKAGE_NAME "slam")
set(CPACK_DEBIAN_PACKAGE_NAME "slam")
set(CPACK_PACKAGE_CONTACT "deeprobotic.cn")
set(CPACK_DEBIAN_PACKAGE_MAINTAINER "deeprobotic.cn")
set(CPACK_PACKAGE_VERSION ${CPACK_PACKAGE_VERSION_MAJOR}.${CPACK_PACKAGE_VERSION_MINOR}.${CPACK_PACKAGE_VERSION_PATCH})
set(CPACK_PACKAGE_FILE_NAME ${CPACK_PACKAGE_NAME}-${CPACK_PACKAGE_VERSION}${PRE_RELEASE_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR})
set(CPACK_DEBIAN_PACKAGE_CONTROL_EXTRA "${CMAKE_CURRENT_SOURCE_DIR}/../scripts/self/preinst;${CMAKE_CURRENT_SOURCE_DIR}/../scripts/self/postinst")


install(DIRECTORY ../scripts
  DESTINATION ${CMAKE_INSTALL_PREFIX})

install(FILES ../change_log.md ../version
  DESTINATION ${CMAKE_INSTALL_PREFIX})

INCLUDE(CPack)

